name: Common workflow
on:
  workflow_call:
    inputs:
      package:
        description: Package to update
        required: true
jobs:
  update:
    name: Update ${{ inputs.package }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - if: matrix.os == 'ubuntu-latest'
      name: Config git for github-actions
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Update ${{ inputs.package }}
      run: |
        cd pkgs/${{ inputs.package }}
        sh update.sh
    - name: Commit and push changes.
      run: |
        if [ "$(git status --porcelain)" ]; then
          git add .;
          git commit -m "action: update ${{ inputs.package }}";
          git push;
        fi
    strategy:
      matrix:
        os:
          - ubuntu-latest
